# Generated by Django 5.1.2 on 2024-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics_provider_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="scheduled_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
