# Generated by Django 5.1.2 on 2024-10-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics_provider_core", "0002_booking_scheduled_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="logistics_provider_core.driver",
            ),
        ),
    ]
