# Generated by Django 5.1.2 on 2024-10-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics_provider_core", "0003_alter_booking_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logisticaccountuser",
            name="is_driver",
        ),
    ]
