# Generated by Django 5.1.2 on 2024-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics_provider_core", "0004_remove_logisticaccountuser_is_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIKE", "Bike"),
                    ("CAR", "Car"),
                    ("VAN", "Van"),
                    ("TRUCK", "Truck"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
